@extends('web.layouts.principal')
@section('content')

@include('web.partials.breadcrumb', ['titulo' => 'Políticas de Privacidad'])

<section class="privacy-area py-5" style="padding-top: 60px; padding-bottom: 60px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="privacy-content" style="background: #fff; border-radius: 15px; padding: 40px; box-shadow: 0 5px 15px rgba(0,0,0,0.05);">
                    <h2 style="font-weight: 700; color: #a30f25; margin-bottom: 30px;">Políticas de Privacidad</h2>
                    
                    <div style="font-size: 16px; color: #555; line-height: 1.8;">
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 25px; text-align: right; font-style: italic;">Última actualización: 31 de julio de 2025.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">1. Información General</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La Universidad Privada de Trujillo – UPRIT identificada con RUC N° 20482309381 y con domicilio en Carretera Industrial Km. 4.0, distrito de Laredo, provincia de Trujillo y departamento La Libertad, es una institución educativa privada que imparte educación superior universitaria, se dedica al estudio, investigación y la difusión del saber y la cultura, así como, a la producción de bienes y servicios que la comunidad nacional, regional y local demandan, lo que conlleva a que sus acciones demuestren organización, disciplina, eficiencia, puntualidad, excelencia académica de calidad y respeto y cumplimiento del ordenamiento jurídico.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La Universidad está a la vanguardia de la innovación jurídica que busca la tutela oportuna de los derechos de los ciudadanos quienes se vinculan con distintas instituciones privadas y públicas y, en ese intercambio de prestación de bienes y servicios, existe una transferencia de información privada y sensible y que merece la tutela por parte de la Universidad.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Ello impulsa que la UPRIT busque la excelencia en sus procedimientos internos y en la gestión de sus relaciones con su comunidad universitaria y terceras personas promoviendo la tutela efectiva de información y datos personales a los que tiene acceso la Universidad a través de distintas plataformas, página web, UPRIT BOT, relaciones contractuales, relaciones laborales, estudiantes, prospecto de estudiantes, de manera presencial, telefónica y/o virtual, entre otros.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La UPRIT es titular de los bancos de datos personales y responsable del tratamiento de aquellos datos que recopila y está comprometida con el cumplimiento Ley N° 29733, Ley de Protección de Datos Personales (“LPDP”) y sus normas reglamentarias para el tratamiento de esa información. En atención a lo señalado, la UPRIT pone a disposición su reciente y vigente Política de Privacidad y Protección de Datos Personales (“Política”).</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">2. Finalidad</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Cumplir con la legislación en materia de protección de datos personales y dotar a la comunidad universitaria y terceras personas de una regulación para el tratamiento y protección de los datos personales y sensibles compartidos a la Universidad, así como establecer las medidas de seguridad a cargo de la Universidad en esta materia.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">3. Alcance</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Esta Política es aplicable a toda actividad de tratamiento de datos personales que realicen los órganos de gobierno y las autoridades de la Universidad, personal docente y administrativo, bajo cualquier modalidad de contratación, estudiantes de pregrado y posgrado, y cualquier persona que mantenga un vínculo con la UPRIT.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">4. Tratamiento de datos personales</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Los principios rectores que rigen el tratamiento de datos personales por parte de la UPRIT son los previstos en la LPDP y sus normas reglamentarias y siendo los siguientes: legalidad, consentimiento, finalidad, proporcionalidad, calidad, seguridad, disposición de recurso y nivel de protección adecuado.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Los datos personales que recopila o puede recopilar la UPRIT, a través de sus plataformas de META, página web, BOT y/o medios convencionales (formularios físicos, llamadas telefónicas), serán almacenados en los correspondientes bancos de datos, ubicados en su domicilio fiscal, y que han sido debidamente declarados a la Autoridad Nacional de Protección de Datos Personales.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La información recopilada puede incluir detalles respecto a las páginas internas accedidas en el sitio web de la UPRIT y las páginas externas que dirigieron al usuario a la página web de la Universidad, así como datos sobre el navegador utilizado y la ubicación geográfica del usuario, la URL de la que proviene el Usuario (incluyendo las externas al sitio web), las URLs más visitadas por el Usuario (incluyendo las externas al sitio web), direcciones IP, información sobre aspectos operativos del sitio web, como análisis y estadísticas de navegación, tráfico, entre otros. Esta información se recopila con la finalidad de mejorar la de navegación y determinar aspectos tales como el formato a emplear en la página web, los productos y servicios que puede brindar de manera virtual, la solución de problemas que pueda presentar el sitio web para determinados usuarios.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Al registrar sus datos personales en los formularios de las plataformas de la UPRIT o al brindarlos de manera convencional, el titular de los datos garantiza que la información proporcionada es exacta, veraz y se encuentra vigente. Cada titular es responsable por la veracidad, exactitud y vigencia de los datos personales suministrados a la UPRIT. La UPRIT podrá verificar la veracidad de los datos personales facilitados, no siendo de responsabilidad de la Universidad la veracidad de la información proporcionada por el titular, por lo que tampoco asume responsabilidad alguna por posibles daños o perjuicios que pudieran originarse por el uso de dicha información.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">5. Consentimiento</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">El consentimiento para el tratamiento de datos personales se obtendrá de manera libre, previa, expresa inequívoca e informada. La UPRIT informará al titular, de manera previa a la recopilación de sus datos personales, sobre las finalidades para las que estos serán tratados.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Los datos personales recogidos se tratan conforme a la finalidad señalada al momento de su recopilación. No se efectúa tratamiento de datos para una finalidad distinta a la informada en su recopilación, consentimiento del usuario o titular del dato. La UPRIT siempre requerirá el consentimiento expreso del usuario para finalidades secundarias como acciones comerciales de prospección y publicidad.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">El titular de datos declara y acepta que, en los avisos correspondientes previstos en cada formulario web o de las aplicaciones de la UPRIT o en los formularios físicos, está otorgando su consentimiento expreso para que la UPRIT trate sus datos personales, según las finalidades descritas en cada formulario y en esta política.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">El conocimiento y aceptación de la presente Política evidencia que el titular de los datos personales recopilados ha brindado su consentimiento para que la UPRIT realice el tratamiento de sus datos personales, según las finalidades complementarias de los formularios web, de los aplicativos, del BOT y/o físicos.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Si el usuario utiliza alguna de las plataformas de orientación de la UPRIT para iniciar interacción con el UPRIT BOT y solicita el apoyo del BOT para iniciar su proceso de postulación, para lo cual realiza el envío de documentos personales (p. ej. copia del DNI, del registro de notas escolares, entre otros), se informará al usuario de dicha plataforma la finalidad de la recolección de dichos documentos que contienen datos personales y se le enviará un enlace para que pueda revisar y aceptar de manera expresa la presente Política en dicho momento.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">No se requiere consentimiento del titular para tratar datos en el ejercicio de las funciones de la UPRIT o para la ejecución de contratos ni por otra razón prevista en el Artículo 14° de la LPDP.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">6. Finalidad de Tratamiento de datos personales</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Dependiendo del perfil del titular de datos personales, los datos recopilados serán tratados con las siguientes finalidades:</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">6.1. Estudiantes y padres de estudiantes menores de edad y egresados</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Gestión académica; gestión administrativa; gestión comercial; gestión y acciones de cobranza; gestión de iniciativas empresariales; gestión de la bolsa de trabajo; gestión de procedimientos disciplinarios; gestión de relaciones con estudiantes inscritos y egresados; ofrecimiento y prestación de servicios educativos u otros ofrecidos por la UPRIT o terceros con quienes se hubieran celebrado contratos o convenios; atención de consultas, quejas, reclamos; registro y actualización de los datos de alumnos y egresados; evaluación socioeconómica para la asignación de escalas de pensiones, becas o cualquier tipo de financiamiento educativo; evaluación del cumplimiento de requisitos para acceder a cualquier beneficio proporcionado por la UPRIT; diseño, ejecución y análisis de encuestas; acreditación académica o de procesos internos, ante instituciones nacionales e internacionales, públicas y privadas; obtención de grados académicos, títulos profesionales, certificaciones y constancias; elaboración y entrega de carnés u otro instrumento de identificación física o digital; entrega y recojo de materiales académicos, documentos, premios y otros artículos que resulten necesarios para el estudiante o egresado; elaboración y entrega de cartas de recomendación; invitaciones a eventos, talleres, charlas o cualquier otro que organice la UPRIT; atención en el tópico; ejecución de actividades de telemarketing, mediante sistemas de llamadas telefónicas, envío de mensajes de texto a celular, mensajería instantánea (WhatsApp), correos electrónicos (individuales o masivos) o medios electrónicos, para promover los productos y servicios educativos; coordinaciones para el desarrollo de eventos organizados por la UPRIT; elaboración y actualización del directorio de la comunidad universitaria; registro como practicante, trabajador o proveedor de servicios a la UPRIT; cumplimiento de los requerimientos que efectúe cualquier entidad pública, por mandato legal; cumplimiento de cualquier finalidad directa o indirecta vinculada a su condición de estudiante o egresado de la UPRIT; transferir la información del titular a empresas que brinden servicios basado en infraestructura en la nube a través de Moodle y/o Pirux Hosting, para fines de alojamiento, almacenamiento y procesamiento de información. Este tratamiento es necesario para brindar los servicios que ofrece la Universidad.</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">6.2. Personal docente y administrativo, directores y proveedores</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Gestión académica; gestión administrativa; gestión comercial; gestión y acciones de cobranza; fiscalización del cumplimiento de las obligaciones laborales; pago de remuneraciones y beneficios sociales; cumplimiento de obligaciones legales; gestión y cumplimiento de contratos, convenios y adendas; gestión de la Entidad Prestadora de Salud (EPS) y otras empresas aseguradoras que benefician a los trabajadores o prestadores; evaluaciones de desempeño; encuestas de satisfacción (docente); difusión de logros académicos o profesionales en la página web o redes sociales; registro de asistencia; verificación de la información declarada en la Hoja de Vida; atención e investigación de quejas o denuncias; procedimientos disciplinarios; actividades de integración; capacitaciones, charlas, talleres, conferencias; evaluaciones de salud y seguridad en el trabajo; registro y actualización del directorio de la comunidad universitaria; elaboración y entrega de fotocheck u otro instrumento de identificación física o digital; entrega y recojo de materiales académicos, documentos, premios y artículos de oficina; elaboración de constancias, certificados, cartas de recomendación, cartas de presentación; ejecución de actividades de telemarketing, mediante sistemas de llamadas telefónicas, envío de mensajes de texto a celular, mensajería instantánea (WhatsApp) correos electrónicos (individuales o masivos) o medios electrónicos, para promover productos y servicios educativos; atención al público; evaluaciones financieras para préstamos u otros beneficios; evaluación del cumplimiento de requisitos para acceder a beneficios; cumplimiento de los requerimientos que efectúe cualquier entidad pública, por mandato legal; cumplimiento de cualquier finalidad directa o indirecta vinculada a su condición de trabajador (personal docente o administrativo). En el caso de los postulantes que registran sus datos en los procesos de selección de personal sus datos serán almacenados en la base de datos con el propósito de remitir comunicaciones vinculadas al proceso de selección en el que participa e información vinculada a otros procesos de selección; transferir la información del titular a empresas que brinden servicios basado en infraestructura en la nube a través de Moodle y/o Pirux Hosting, para fines de alojamiento, almacenamiento y procesamiento de información. Este tratamiento es necesario para la ejecución de los servicios que ofrece la Universidad.</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">6.3. Beneficiarios de publicidad y prospección (incluidos potenciales estudiantes menores de edad) y visitantes</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Gestión académica; gestión administrativa; gestión comercial; apoyo a emprendimientos; difusión de campañas de emprendimientos; atención y seguimiento al proceso de postulación y admisión; atención de consultas sobre los procesos de admisión, carreras profesionales, pensiones de enseñanza, financiamiento o de cualquier tipo; atención de reclamos; recopilación de información para determinar la escala de pensiones; registro de postulantes; publicación de resultados de los procesos de admisión en sus diferentes modalidades; diseño, ejecución y análisis de encuestas; registro e inscripción a eventos; ejecución de actividades de telemarketing, mediante sistemas de llamadas telefónicas, envío de mensajes de texto a celular, mensajería instantánea (WhatsApp), correos electrónicos (individuales o masivos) o medios electrónicos cumplimiento de los requerimientos que efectúe cualquier entidad pública, por mandato legal; cumplimiento de cualquier finalidad directa o indirecta vinculada a su condición de postulante a cualquiera de los servicios educativos de la UPRIT; realizar estudios internos sobre los intereses, comportamientos y hábitos de conducta de los titulares a fin de personalizar el contenido y comunicaciones; envío de publicidad siempre que ello haya sido aprobado de manera separada, incondicional, previa, libre, expresa, inequívoca y gratuita; elaborar estudios estadísticos y/o analíticos sobre la operatividad y navegabilidad de las páginas web y aplicativos de la UPRIT para mejorar la experiencia del titular de datos, así como elaborar estudios estadísticos y/o analíticos sobre hábitos de navegación y búsquedas con la finalidad de mejorar los servicios que se brindan en línea; transferir la información del titular a empresas que brinden servicios basado en infraestructura en la nube a través de Moodle y/o Pirux Hosting, para fines de alojamiento, almacenamiento y procesamiento de información. Este tratamiento es necesario para brindar los servicios que ofrece la Universidad.  Con relación al BOT de la Universidad es importante señalar que se trata de un sistema automatizado de respuestas que utiliza inteligencia artificial generativa y que funciona con las plataformas de WhatsApp, Instagram y Facebook Messenger (sin que estas plataformas sean las únicas, pudiéndose ampliar en el tiempo hacia otras plataformas). El sistema de respuestas es un robot que atiende consulta de los usuarios (entiéndase, cualquier persona que inicie la interacción en las plataformas señaladas de la UPRIT) con el fin de solicitar información pública y disponible sobre la oferta educativa, procesos de matrícula y costos. Asimismo, el UPRIT BOT puede guiar al usuario hacia el proceso de envío de documentos para su postulación a una carrera que serán registrados en un sistema y analizados por un agente humano.</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">6.4. Padres y tutores</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Gestión académica; gestión administrativa; gestión comercial; gestión y acciones de cobranza; evaluación socioeconómica para definir la escala de pensiones a la que será asignado el estudiante al que representa; gestión de procedimientos disciplinarios; ejecución de actividades de telemarketing, mediante sistemas de llamadas telefónicas, envío de mensajes de texto a celular, mensajería instantánea (WhatsApp), correos electrónicos (individuales o masivos) o medios electrónicos. En el caso de estudiantes menores de catorce (14) años, sus padres o tutores serán quienes proporcionen los datos personales o información personal de estos menores, con la finalidad de gestionar la participación en las actividades académicas y no académicas a las que sean registrados; contacto en caso de emergencia, accidentes; información sobre el desempeño en las actividades en las que estuviese inscrito, y las notas o calificaciones obtenidas.</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">6.5. Menores de edad (14 años a 17 años)</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Los datos personales de menores de edad de entre 14 y 17 años serán recibidos para de atender su postulación o sus intereses en alguna de las carreras que ofrece la UPRIT, y para gestionar su participación en actividades de su interés.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">En el caso del uso del UPRIT BOT debe tenerse presente que, como se indica en los Términos y Condiciones de Uso del UPRIT BOT (ver página web de la UPRIT), la información que brinda el BOT es general y de carácter informativo, estando a disposición de todos los usuarios, incluyendo menores de edad, sin que el UPRIT BOT recopile datos personales de identificación en esta etapa de consulta. En caso se trate de un usuario menor de edad que desea iniciar un proceso de postulación que implique el envío de documentos personales, aplica lo previsto en la Política, asegurando su oportuna tutela.</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">6.6. Menores de edad (13 años hacia abajo)</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Los datos personales de contacto de menores de edad de entre 5 y 13 años serán proporcionados por los padres de familia o sus apoderados legales. Estos datos se utilizarán únicamente para gestionar la participación de los menores en las actividades académicas en las que sean inscritos. Asimismo, con la finalidad de garantizar la salud y seguridad de los menores se les podrá solicitar información respecto a sus alergias.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Los datos de los padres de familia o apoderados serán almacenados junto con los de los menores de edad con fines de contacto y para mantenerlos informados sobre el desempeño y resultado de sus hijos, de corresponder.</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">6.7. Imágenes recopiladas en eventos de la UPRIT</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">En los eventos que organice la Universidad, el titular autoriza a la UPRIT a utilizar su imagen (en fotografía o video) en su portal institucional, redes sociales, afiches u otro medio de difusión, y que su imagen sea parte de las actividades para la promoción de las actividades y los eventos que se organicen.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">7. Transferencia de Información</h3>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">7.1. Información solicitada por autoridades públicas</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Se podrán transferir los datos personales recopilados por la UPRIT, en virtud de una obligación legal, mandato o requerimiento de una autoridad administrativa o mandato judicial, a instituciones públicas o entidades privadas. No se compartirán los datos personales con terceros no autorizados, salvo consentimiento de el titular del dato recogido por la Universidad.</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">7.2. Transferencia de información a terceros</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Teniendo en cuenta las finalidades descritas y los perfiles de usuario, la UPRIT podrá compartir, ceder, encargar o transferir los datos personales de los titulares a universidades o instituciones educativas en el territorio nacional y extranjero (con quienes mantenga un convenio o acuerdo de colaboración en beneficio de sus estudiantes o comunidad universitaria); asociaciones de egresados; potenciales empleadores y reclutadoras; instituciones vinculadas a la Universidad para el cumplimiento de sus fines y obligaciones legales y contractuales. En cualquier caso, la UPRIT garantiza la confidencialidad y el tratamiento seguro de la información compartida.</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">7.3. Flujo transfronterizo</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La UPRIT declara que podría realizar el flujo transfronterizo, sobre algunos de los datos personales que recopila, a los países de Estados Unidos. El flujo transfronterizo se realiza con la finalidad de integrarse con plataformas tecnológicas, proveedores de servicios de inteligencia artificial, plataformas de computación en la nube, servicios de base de datos distribuidas y/o proveedores de infraestructura tecnológica que brindan soporte a los procesos académicos y administrativos que desarrolla la Universidad, así como la integración con plataformas de marketing para la difusión de comunicaciones con los estudiantes, trabajadores e interesados. El procesamiento y/o almacenamiento de datos personales (incluyendo los documentos de postulación) es inherente al uso de dichos servicios de tecnología.</p>
                        <h4 style="color: #a30f25; font-weight: 600; font-size: 18px; margin-top: 25px; margin-bottom: 15px;">7.4. Transferencia de datos a terceros para finalidades adicionales</h4>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Solo en caso que el titular del dato haya brindado su autorización para finalidades adicionales, los datos personales recopilados por la UPRIT podrán compartirse dentro y fuera del territorio nacional. En cualquier caso, la Universidad garantiza la confidencialidad y el tratamiento seguro de la información compartida.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">8. Empleo de Videovigilancia</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La UPRIT cuenta con cámaras de videovigilancia que registran las incidencias dentro y alrededor de sus instalaciones. Las imágenes y/o voces grabadas se almacenarán por un plazo de treinta (30) días naturales y hasta un plazo máximo de sesenta (60) días naturales, salvo disposición distinta en normas sectoriales. La UPRIT asegura la reserva y confidencialidad de la información, no permitiendo la difusión, copia o visualización de imágenes por terceros no autorizados.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">Los registros en las cámaras de videovigilancia también serán utilizados con la finalidad de supervisar el cumplimiento de obligaciones laborales, control de asistencia o como medio probatorio en procedimientos disciplinarios.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">9. Medidas de Seguridad para resguardar los datos personales</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">De acuerdo con las medidas de seguridad exigidas por el ordenamiento jurídico vigente, la UPRIT ha adoptado las medidas suficientes y adecuadas y se compromete a tratar los datos personales como información confidencial, a fin de prevenir e impedir el acceso o divulgación no autorizada y asegurar el uso apropiado de la información.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La UPRIT ha implementado las medidas de seguridad organizacionales, legales y técnicas (físicas y lógicas) de conformidad con la LPDP a fin de que su personal que efectúa el tratamiento de datos personales guarde la confidencialidad respecto a la información personal a la que accede en el ejercicio de sus funciones. La Universidad garantiza que los terceros que tengan acceso a los datos personales recopilados implementen las medidas de seguridad idóneas para un tratamiento seguro de datos personales.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La UPRIT cuenta con directrices internas a fin de salvaguardar la seguridad en línea, la seguridad física, el riesgo de la pérdida de datos y otros similares, teniendo en cuenta el riesgo que representan el procesamiento y la naturaleza de los datos bajo protección. El acceso a las bases de datos que contienen datos personales se restringe a las personas autorizadas que tengan necesidad de acceder a dicha información.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">No obstante los estándares indicados y los niveles de seguridad y diligencia adoptados por la UPRIT, la Universidad no se hace responsable por interceptaciones ilegales o violación de sus sistemas o bases de datos por parte de personas no autorizadas, así como la indebida utilización de la información obtenida por esos medios, o de cualquier intromisión ilegítima que escape al control de UPRIT y que no le sea imputable.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">10. Derechos del titular de datos personales - Derechos ARCO</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La UPRIT pone a disposición de los titulares de datos la posibilidad de ejercer los derechos que se encuentran contemplados en la LPDP y su reglamento, mediante comunicación escrita dirigida al siguiente correo electrónico: defensoriauniversitaria@uprit.edu.pe, siendo estos derechos los siguientes: Acceso, Rectificación, Cancelación, Oposición, Revocatoria e Información.</p>
                        <p style="color: #a30f25; font-weight: 600; font-size: 16px; margin-bottom: 5px;">(i) Derecho a ser Informado:</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">sobre la finalidad para la cual sus datos personales están siendo tratados, así como los destinatarios de los mismos y el banco de datos donde se almacenan sus datos personales</p>
                        <p style="color: #a30f25; font-weight: 600; font-size: 16px; margin-bottom: 5px;">(ii) Derecho de Acceso:</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">derecho a obtener la información relativa a sus datos personales objeto de tratamiento, así como la forma, motivos y condiciones de su recopilación.</p>
                        <p style="color: #a30f25; font-weight: 600; font-size: 16px; margin-bottom: 5px;">(iii) Derecho de Rectificación:</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">derecho a la corrección de aquellos datos que se encuentren errados o resulten inexactos o falsos.</p>
                        <p style="color: #a30f25; font-weight: 600; font-size: 16px; margin-bottom: 5px;">(iv) Derecho de Cancelación:</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">derecho a solicitar la supresión de sus datos personales de las bases de datos de la UPRIT cuando ya no sean necesarios o pertinentes para la finalidad que fueron recopilados, el plazo para su tratamiento hubiere vencido, el titular haya revocado su consentimiento; o, cuando no sean tratados conforme a la legislación de la materia.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La solicitud de cancelación de tratamiento de datos personales (ej. los recopilados en el UPRIT BOT o formularios de prospección y documentos de postulantes no matriculados) de los usuarios que postulan a través del BOT pero que no llegan a ser alumnos serán eliminados de los registros de prospección y postulación a su solicitud remitida al correo electrónico:defensoriauniversitaria@uprit.edu.pe.</p>
                        <p style="color: #a30f25; font-weight: 600; font-size: 16px; margin-bottom: 5px;">(v) Derecho de Oposición:</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">derecho a que no se traten sus datos personales o cese su tratamiento cuando no se haya prestado su consentimiento para el mismo o cuando estos se hubieran obtenido de una fuente de acceso público. Si el titular prestó su consentimiento, podrá oponerse al tratamiento de sus datos por motivos fundados y legítimos.</p>
                        <p style="color: #a30f25; font-weight: 600; font-size: 16px; margin-bottom: 5px;">(vi) Derecho de Revocatoria:</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">derecho a anular o cancelar el consentimiento brindado para el tratamiento de sus datos personales en cualquier momento, sin justificación previa y sin que le atribuyan efectos retroactivos.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">12. Empleo de cookies</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La página web de la Universidad podrá funcionar con cookies que son archivos de datos que se instalan en el dispositivo móvil o en la computadora para almacenar y recuperar información del usuario cuando usa la página web o aplicación de la Universidad. UPRIT podrá emplear cookies para guardar información de acceso para futuras conexiones a los sitios webs y sus diversas aplicaciones.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">El uso de cookies no permite revelar los datos personales de las personas que acceden a la página web o aplicaciones.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La UPRIT garantiza el mismo tratamiento a la información obtenida por medio del empleo de cookies que a la de datos personales, tutelando la confidencialidad y seguridad de dicha información.</p>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">El usuario podrá activar o desactivar el uso de cookies a través de su navegador; sin embargo, dicha desactivación podría generar que la web o aplicativo de la UPRIT no funcione a cabalidad.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">13. Notificación de incidentes de seguridad</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">En el supuesto que la Universidad detecte un incidente de seguridad respecto de los datos personales, informará este hecho a la Autoridad Nacional de Protección Datos Personales; asimismo, informará al titular de los datos personales sobre el incidente, así como las medidas para mitigar sus efectos.</p>
                        <h3 style="color: #a30f25; font-weight: 700; font-size: 20px; margin-top: 35px; margin-bottom: 20px;">14. Modificaciones de la política</h3>
                        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 15px; text-align: justify;">La UPRIT se reserva el derecho a modificar o actualizar en cualquier momento la presente Política. Cualquier modificación o actualización en la presente Política será publicada en la página web de la Universidad.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection
