<?php

return [
    'hero' => [
        'titulo' => 'Ciencia e Innovación para un Futuro Sostenible',
        'descripcion' => 'En la UPRIT promovemos una cultura de investigación, innovación y emprendimiento científico que integra a estudiantes, docentes y aliados estratégicos para desarrollar proyectos multidisciplinarios, generar nuevo conocimiento y contribuir al desarrollo sostenible de la región y del país.',
    ],

    'repositorio_url' => 'https://repositorio.uprit.edu.pe/handle/UPRIT/208',

    'ejes' => [
        'titulo' => 'Ejes Estratégicos de la Investigación',
        'intro' => 'En este apartado se presentan los ejes estratégicos que orientan y articulan las actividades de investigación de la Dirección de Investigación.',
    ],

    'colaboracion_internacional' => [
        'titulo' => 'Colaboración Internacional',
        'intro' => 'Instituciones con convenios y acuerdos de cooperación vinculados con investigación, cooperación científica, intercambio académico y producción de conocimiento.',
        'descripcion' => 'Los convenios suscritos por la Universidad pueden comprender diferentes ámbitos de cooperación institucional. En esta sección se destacan aquellos con vinculación o contribución relevante al desarrollo de actividades de investigación.',
        'convenios' => [
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Instituto Imperial'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y la Asociación de Pequeños y Medianos Industriales del Perú - Filial Arequipa'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Banco BANBIF'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Sindicato Mixto de Unidad de Trabajadores del Poder Judicial Lima'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y Oftalmovisión S.A.C.'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y la Clínica Dr. Luis Quito'],
            ['nombre' => 'Convenio Específico de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Centro Médico Dr. Luis Quito'],
            ['nombre' => 'Convenio Específico entre la Universidad Privada de Trujillo y CYPE Ingenieros, S.A.C.'],
            ['nombre' => 'Convenio Marco de Cooperación Institucional entre la Universidad Privada de Trujillo y la Asociación de Estudiantes de Derecho del Perú'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y la Cámara de Comercio de La Libertad'],
            ['nombre' => 'Convenio Marco de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y Glexco Robotics and Automation S.A.C.'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Colegio de Psicólogos del Perú - CDR VII'],
            ['nombre' => 'Convenio Específico de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Consultorio Dental A. J.'],
            ['nombre' => 'Convenio Marco de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Instituto de Educación Tecnológico Privado FERCP'],
            ['nombre' => 'Convenio Marco de Cooperación Interinstitucional entre la Universidad Privada de Trujillo e Inversiones Turísticas Santa Inés S.A.C.'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Colegio de Abogados de La Libertad'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Colegio de Ingenieros del Perú - Consejo Departamental de La Libertad'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Colegio de Abogados de Sullana'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Colegio Regional de Licenciados en Administración La Libertad'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y el Colegio de Contadores Públicos de La Libertad'],
            ['nombre' => 'Convenio de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y Servicios Educativos Generales Trujillo E.I.R.L.'],
            ['nombre' => 'Convenio Marco de Cooperación Interinstitucional entre la Universidad Privada de Trujillo y Innovación y Desarrollo Alzamora de los Grados Consultoría y Editorial E.I.R.L.'],
        ],
    ],

    'produccion_cientifica' => [
        'titulo' => 'Producción Científica',
        'intro' => 'Principales proyectos de investigación y productos científicos desarrollados por la UPRIT, promoviendo la generación, difusión y acceso al conocimiento.',
        'descripcion' => 'Creamos un entorno para la producción científica, buscando posicionar a UPRIT como un referente de conocimiento y vanguardia.',
        'proyectos_titulo' => 'Proyectos de Investigación I+D+i – 2025–2026',
        'proyectos' => [
            [
                'titulo' => 'Probabilidades de Daños en Estructuras de Sistema Estructural Dual Frente a Sismos de Gran Magnitud, Lima – 2025',
                'investigador_principal' => 'Dr. Lenin Miguel Bendezú Romero',
                'coautores' => 'Enrique Manuel Durand Bazán',
                'linea' => 'Gestión, Innovación, Infraestructura Sostenible y Sistemas Constructivos',
                'producto' => 'Artículo científico',
                'anio' => '2025',
            ],
            [
                'titulo' => 'Percepciones Parentales y Propuesta Pedagógica para Fomentar la Identidad Cultural',
                'investigador_principal' => 'Dra. Olga Estela Mendoza León',
                'coautores' => 'Celina Pérez Mena, Carlos Diego León Villacorta',
                'linea' => 'Innovación, Tecnologías, Metodologías y Procesos Pedagógicos, Gestión y Calidad Educativa',
                'producto' => 'Artículo científico',
                'anio' => '2025',
            ],
            [
                'titulo' => 'Sistema Multimodal de Seguridad Vehicular Basado en Reconocimiento Facial y Control de Encendido para Vehículos usando Microcomputadoras de Bajo Consumo',
                'investigador_principal' => 'Mg. Charlen Máximo Calero Huamán',
                'coautores' => 'Cecilia Marieta Lezama Sánchez',
                'linea' => 'Sistemas y Seguridad de la Información, Inteligencia Artificial, Desarrollo de Procesos Industriales, Gestión de Proyectos, Riesgos y Sostenibilidad Ambiental',
                'producto' => 'Artículo científico',
                'anio' => '2025',
            ],
            [
                'titulo' => 'Plataforma de Monitoreo de Salud Emocional Estudiantil a través de Análisis de Voz y Expresiones Faciales',
                'investigador_principal' => 'Mg. Antonio Manfredi Fernández Figueroa',
                'coautores' => 'Alexander Máximo Rodríguez García, Paula Alexandra La Barrera Neciosup',
                'linea' => 'Emprendimiento, Gestión Empresarial y Pública, Finanzas, Tributación, Auditoría y Competitividad',
                'producto' => 'Artículo científico',
                'anio' => '2025',
            ],
            [
                'titulo' => 'Gestión de la Innovación con Tecnología Financiera en el Crecimiento de la Mypes de Calzado Peruanas',
                'investigador_principal' => 'Dra. Olenka Ana Catherine Espinoza Rodriguez',
                'coautores' => 'Marco Antonio Sevilla Gamarra, Mirtha Zulema Armas Chang, Luigi Ítalo Villena Zapata',
                'linea' => 'Emprendimiento, Gestión Empresarial y Pública, Finanzas, Tributación, Auditoría y Competitividad',
                'producto' => 'Artículo científico',
                'anio' => '2025',
            ],
            [
                'titulo' => 'Smart contracts y seguridad jurídica en el Perú: análisis de su viabilidad en el sistema legal peruano',
                'investigador_principal' => 'Carlos Jesús Alza Collantes',
                'coautores' => 'Ghandy Allizon Rengifo Calvanapon, Gustavo Antero Silva, Kuo-Ying Fabrizio Alonso Morales Novoa',
                'linea' => 'Eficiencia de Justicia, Derecho, Estado y Gestión Pública',
                'producto' => 'Artículo científico',
                'anio' => '2026',
            ],
            [
                'titulo' => 'Uso de geosintético y residuos de concreto estructural como aditivo estabilizador de subrasantes débiles: Estudio experimental y modelo de regresión múltiple',
                'investigador_principal' => 'Luigi Ítalo Villena Zapata',
                'coautores' => 'Rolando Fuentes Llave, Álvaro Gustavo Amaya Álvarez, Wilson Rolando Cruz Quezada, Juan Martín García Chacero, Marlon Gastón Farfán Córdova',
                'linea' => 'Gestión, Innovación, Infraestructura Sostenible y Sistemas Constructivos',
                'producto' => 'Artículo científico',
                'anio' => '2026',
            ],
            [
                'titulo' => 'Estrategias de Ciencias y Tecnología en el desarrollo de habilidades investigativas de una Institución Educativa en Trujillo, 2026',
                'investigador_principal' => 'Renzo Jesus Maldonado Gomez',
                'coautores' => 'Julio César Cueva Torres, Karin Araceli Valverde Reyes, Luigi Ítalo Villena Zapata',
                'linea' => 'Innovación, Tecnologías, Metodologías y Procesos Pedagógicos, Gestión y Calidad Educativa',
                'producto' => 'Artículo científico',
                'anio' => '2026',
            ],
            [
                'titulo' => 'Desarrollo de un sistema IoT con Microcontrolador ARM Cortex y su efecto sobre la detección de pérdidas de eficiencia energética',
                'investigador_principal' => 'Charlen Máximo Calero Huamán',
                'coautores' => 'Joffre Hugo Vara Chávez',
                'linea' => 'Sistemas y Seguridad de la Información, Inteligencia Artificial, Desarrollo de Procesos Industriales, Gestión de Proyectos, Riesgos y Sostenibilidad Ambiental',
                'producto' => 'Artículo científico',
                'anio' => '2026',
            ],
            [
                'titulo' => 'Incidencia del valor de la marca en la adopción de billeteras móviles en empresas comercializadoras de calzado, Trujillo 2026',
                'investigador_principal' => 'Mirtha Zulema Armas Chang',
                'coautores' => 'Luigi Ítalo Villena Zapata, Olenka Ana Catherine Espinoza Rodriguez, Marco Antonio Sevilla Gamarra',
                'linea' => 'Emprendimiento, Gestión Empresarial y Pública, Finanzas, Tributación, Auditoría y Competitividad',
                'producto' => 'Artículo científico',
                'anio' => '2026',
            ],
            [
                'titulo' => 'Efectos de un programa de prevención en adicciones tecnológicas sobre la carga cognitiva en adolescentes, Trujillo 2026',
                'investigador_principal' => 'Jacqueline Roxana Romero Reyna',
                'coautores' => 'Anita Campos Márquez, Luigi Ítalo Villena Zapata, Kenia Andreina Muñoz Flores, Natalia Mavila Rodríguez Guzmán',
                'linea' => 'Emprendimiento, Gestión Empresarial y Pública, Finanzas, Tributación, Auditoría y Competitividad',
                'producto' => 'Artículo científico',
                'anio' => '2026',
            ],
        ],
    ],

    'investigacion_rsu' => [
        'titulo' => 'Investigación con Responsabilidad Social Universitaria',
        'intro' => 'La Dirección de Investigación promueve proyectos que articulan la generación de conocimiento con la atención de necesidades y problemáticas de la sociedad, contribuyendo al desarrollo sostenible y al fortalecimiento de la Responsabilidad Social Universitaria.',
        'descripcion' => 'Nuestros proyectos impulsan la innovación en ciencia, tecnología, agricultura, humanidades y más, beneficiando al país y al mundo.',
        'proyectos' => [
            [
                'titulo' => 'Gestión de la Innovación con Tecnología Financiera en el Crecimiento de la Mypes de Calzado Peruanas',
                'investigador_principal' => 'Dra. Olenka Ana Catherine Espinoza Rodriguez',
                'coautores' => 'Marco Antonio Sevilla Gamarra, Mirtha Zulema Armas Chang, Luigi Ítalo Villena Zapata',
                'linea' => 'Emprendimiento, Gestión Empresarial y Pública, Finanzas, Tributación, Auditoría y Competitividad',
                'aliado' => 'Asociación APIAT',
                'producto' => 'Software',
            ],
        ],
    ],

    'columna' => [
        'titulo' => 'Columna del Investigador',
        'intro' => 'Un espacio para compartir ideas, reflexiones y perspectivas de nuestros docentes e investigadores sobre ciencia, investigación, educación, innovación y temas de interés para la sociedad.',
        'articulos' => [
            [
                'slug' => 'grado-de-doctor',
                'docente_nombre' => 'Marco Antonio Sevilla Gamarra',
                'titulo' => 'El Grado de Doctor: Compromiso con la Ciencia y el Desarrollo de la Sociedad',
                'parrafos' => [
                    'El grado académico de Doctor representa el valor de una especial dedicación al estudio y a la investigación científica, constituye un nivel de perfeccionamiento de la más alta calidad, constituyendo un grado de excelencia en su más alto nivel cuya función específica es la reflexión filosófica sobre el área profesional correspondiente, que orienta con su cuestionamiento filosófico tanto a la ciencia, al arte y las humanidades para la renovación de conocimiento.',
                    'El Doctor es el más alto grado académico que ostenta en su respectiva profesión; contribuye al desarrollo de la ciencia y a la investigación científica del país, genera métodos y teorías dando solución a problemas científicos, es un líder en su área de conocimiento. El grado de doctor en una determinada especialidad es producto de haber cursado y aprobado satisfactoriamente seis semestres académicos, haber sustentado una tesis de investigación original, inédita y crítica, y haber acreditado el conocimiento de tres idiomas.',
                    'El Doctor es netamente un investigador de alto nivel, un conector de la ciencia, un epistemólogo, erudito, sabio, eminencia, ilustrado, docto, culto, letrado, persona que enseña y cultiva una ciencia o arte, genera nuevos conocimientos y los aplica, es un hombre de ciencia. El doctor por “Honoris Causa” es un título dado a personas eminentes.',
                    'El doctorado es el motor de la ciencia y el desarrollo, prepara investigadores de alto nivel, siendo de un nivel especial: problematiza un área de conocimiento, o bien tiene una dimensión de suma significación, sea para la sociedad, la humanidad, contribuyendo al desarrollo regional o nacional del país.',
                ],
                'cita' => 'Ser doctor no solo significa alcanzar el más alto grado académico, sino asumir la responsabilidad de producir conocimiento con impacto para la sociedad.',
            ],
            [
                'slug' => 'inteligencia-artificial-etica',
                'docente_nombre' => 'Olenka Ana Catherine Espinoza Rodriguez',
                'titulo' => 'Uso de Inteligencia Artificial y Ética en la Producción Científica de la Educación Superior',
                'parrafos' => [
                    'La incorporación de la inteligencia artificial (IA) en la educación superior peruana representa mucho más que un avance tecnológico: constituye una transformación que invita a replantear la forma en que se enseña, se aprende y se genera conocimiento. Herramientas de IA generativa como ChatGPT, Gemini, Copilot y Claude, entre otras, ofrecen oportunidades para personalizar el aprendizaje, fortalecer la investigación y ampliar el acceso a la información. Sin embargo, su uso también plantea desafíos éticos que no pueden pasar desapercibidos, entre ellos el fraude académico, la desinformación, la pérdida de autenticidad en la producción intelectual y el riesgo de delegar a la tecnología decisiones que requieren criterio humano.',
                    'En este contexto, la producción científica enfrenta nuevos retos y, al mismo tiempo, nuevas oportunidades. La IA debe concebirse como una herramienta de apoyo cuyo uso esté orientado por el pensamiento crítico, la integridad académica y la supervisión humana. El docente, además de impartir conocimientos, asume el rol de guía y constructor ético del proceso de enseñanza-aprendizaje. La responsabilidad del maestro es orientar, acompañar y promover una formación reflexiva que permita a los estudiantes analizar, cuestionar y contextualizar la información generada por la IA, asegurando que la tecnología complemente el aprendizaje sin reemplazar el juicio, la originalidad, la creatividad ni la responsabilidad compartida entre docentes y estudiantes.',
                    'En esta nueva realidad digital, la excelencia académica no depende de adoptar o rechazar la inteligencia artificial, sino de utilizarla con responsabilidad, transparencia y sentido ético. El verdadero desafío consiste en integrar estas herramientas de manera que potencien el ingenio y la capacidad investigativa, sin sustituir la reflexión crítica ni la autoría intelectual. Por ello, resulta indispensable promover una cultura de honestidad académica en la que el uso de la IA sea reconocido y declarado de forma explícita para construir una educación más humana, íntegra y justa, garantizando que la tecnología sea siempre una herramienta al servicio del aprendizaje y del desarrollo del pensamiento crítico, y nunca un sustituto de la esencia humana.',
                ],
                'cita' => 'La excelencia académica no depende de adoptar o rechazar la inteligencia artificial, sino de utilizarla con responsabilidad, integridad y sentido ético.',
            ],
            [
                'slug' => 'estadistica-lenguaje-evidencia',
                'docente_nombre' => 'Luigi Italo Villena Zapata',
                'titulo' => 'La Estadística como Lenguaje de la Evidencia',
                'parrafos' => [
                    'La estadística es una base clave para la formación universitaria y la investigación científica; sin embargo, impartir esta materia conlleva una contradicción: se prioriza la aplicación del método antes que interpretar la evidencia. Procesar datos es automático; reflexionar, un proceso humano. Debido a esto, el déficit se mantiene: aun los profesionales que utilizan la estadística cotidianamente continúan leyendo erróneamente las pruebas de significancia. El origen del problema no es de índole técnica, sino que reside en un modelo de enseñanza que prioriza el método por encima del pensamiento.',
                    'Un error frecuente lo evidencia con claridad. Se interpreta un valor p superior al umbral como demostración de que la hipótesis nula es verdadera, concluyendo así que no existe efecto alguno. La realidad es opuesta: el valor p cuantifica la probabilidad de observar los datos obtenidos bajo el supuesto de que la nula fuese cierta, y no la probabilidad de que una hipótesis lo sea. Por lo tanto, un resultado no significativo no valida la ausencia de un efecto; únicamente denota que la evidencia recolectada es insuficiente para rechazar dicha hipótesis. Cuando superar el umbral se convierte en el objetivo, la lógica se invierte y los datos dejan de someter la hipótesis a prueba para pasar a confirmarla de forma sesgada.',
                    'Expandir los contenidos del temario no subsana un problema que radica en la forma de aprender a razonar. La solución pasa por reorientar la mirada hacia la esencia de la investigación: formular preguntas adecuadas, conocer la procedencia de los datos e interpretarlos en su contexto. Asimismo, conviene mejorar la comunicación de resultados: informar únicamente si un hallazgo superó determinado umbral reduce la evidencia a una respuesta afirmativa o negativa, mientras que el tamaño del efecto y los intervalos de confianza revelan su magnitud y su precisión.',
                    'Tras los datos hay personas y decisiones cuyas consecuencias trascienden el artículo científico. La transparencia metodológica sustenta la credibilidad de la ciencia. La estadística es el lenguaje mediante el cual la ciencia razona ante la ausencia de certezas: enseñarla con rigor no implica ofrecer respuestas definitivas, sino delimitar el alcance de la evidencia. Mientras la obtención de significancia estadística reemplace a la genuina interrogante de investigación, se continuará confundiendo la precisión técnica con la verdadera comprensión.',
                ],
                'cita' => 'La calidad de una investigación no depende únicamente del análisis de los datos, sino de la capacidad para interpretar la evidencia con rigor científico.',
            ],
            [
                'slug' => 'investigacion-motor-soluciones',
                'docente_nombre' => 'Mirtha Zulema Armas Chang',
                'titulo' => 'La Investigación como Motor de Soluciones y Mejora Continua en las Organizaciones',
                'parrafos' => [
                    'En un mundo tan competitivo, donde el entorno para las organizaciones muestra paralelamente oportunidades y desafíos, se hace propicio identificar problemas y buscar soluciones, y en este punto es donde la investigación toma realce, debido a que a través de ella se ingresa a cada realidad organizacional y se toma conocimiento del contexto que atraviesan y de sus participantes involucrados. A través de la historia, en distintas bases de datos consultamos revistas científicas y encontramos muchas realidades, problemas y también soluciones que la investigación ha proporcionado a través del recojo de información y tratamiento de sus datos.',
                    'Si en la actualidad conocemos por qué existen organizaciones más competitivas que otras o por qué los colaboradores se sienten más satisfechos, felices o estresados en algunas empresas, es gracias a la investigación. También se conocen estrategias, talleres y distintas recomendaciones que los investigadores dejan a disposición de la sociedad y el mundo empresarial en aras de aportar al conocimiento, que es el objetivo de la investigación. Asimismo, la investigación fortalece la capacidad de las organizaciones para tomar decisiones fundamentadas en evidencia, comprender mejor su entorno y responder de manera oportuna a los cambios que se presentan.',
                    'Cada estudio constituye una oportunidad para identificar oportunidades de mejora, impulsar la innovación y generar conocimientos que contribuyan al crecimiento organizacional y al desarrollo de la sociedad. Existen muchas investigaciones con grandes aportes; sin embargo, la sociedad líquida que rodea a las organizaciones hace preciso que sea una continua búsqueda de la mejora continua.',
                ],
                'cita' => 'Las organizaciones que investigan no solo comprenden sus problemas; desarrollan soluciones y construyen ventajas sostenibles.',
            ],
            [
                'slug' => 'legado-virtualidad-pandemia',
                'docente_nombre' => 'Renzo Jesus Maldonado Gomez',
                'titulo' => 'La Transformación de la Educación Superior: El Legado de la Virtualidad Después de la Pandemia',
                'parrafos' => [
                    'La pandemia de COVID-19 señaló un hito en la educación universitaria: inicialmente se consideraba un componente periférico, pero posteriormente se transformó en el núcleo de la pedagogía, fomentando la transformación digital, la formación de los docentes y la ampliación de la cobertura educativa. Antes de la pandemia, la educación en línea se percibía como una opción secundaria, predominantemente en programas de posgrado o programas de educación continua. Precisar, cientos de docentes mostraban una preferencia por los métodos tradicionales y las instituciones universitarias no realizaban las inversiones necesarias en infraestructura digital.',
                    'Era evidente la cobertura limitada: la accesibilidad estaba determinada por la conectividad y la disponibilidad de recursos tecnológicos, factores que propiciaban una desigualdad significativa. Asimismo, predominaba en la época una incipiente innovación, donde existían iniciativas de aprendizaje electrónico, no obstante, carecían de un modelo pedagógico robusto y de políticas de integración claras. Con la llegada de la pandemia de COVID-19, se observó una aceleración notable en la educación virtual, atribuible al empleo de las Tecnologías de la Información y la Comunicación (TIC).',
                    'Este entorno facilitó la instauración de innovadoras estrategias pedagógicas en el ámbito de la educación superior, particularmente en las instituciones universitarias, las cuales se vieron obligadas a adaptarse con prontitud a modalidades no presenciales. Así, el paradigma educativo convencional se transformó en la educación virtual, fundamentada en la utilización de plataformas digitales, herramientas tecnológicas y recursos en línea que aseguraron la continuidad del proceso educativo durante la emergencia sanitaria. Además, esta transformación catalizó procesos de digitalización que transformaron la metodología de enseñanza y aprendizaje en el contexto universitario.',
                    'Se evidenció que las universidades efectuaron una migración expedita hacia plataformas como Zoom, Moodle o Microsoft Teams. Se promovieron programas de capacitación en habilidades digitales con el objetivo de asegurar la continuidad académica. Por otro lado, se constató la disparidad digital, particularmente en regiones rurales y entre estudiantes con recursos limitados. Se procedió a la reconsideración de los métodos de evaluación, interacción y asistencia estudiantil en línea.',
                    'En la actualidad, la educación virtual constituye un elemento constante en las universidades; incluso algunas adoptaron el modelo híbrido (presencial + virtual) y se intensificó la inversión en infraestructura tecnológica y en políticas orientadas, en especial, a la formación digital para la enseñanza en línea.',
                ],
                'cita' => 'La pandemia transformó la forma de enseñar; la innovación digital transformó la manera de aprender.',
            ],
            [
                'slug' => 'salud-mental-era-digital',
                'docente_nombre' => 'Jacqueline Roxana Romero Reyna',
                'titulo' => 'Salud Mental en la Era Digital: El Desafío de Conectar sin Desconectarnos',
                'parrafos' => [
                    'El Ministerio de Salud (MINSA) advierte que más peruanos padecen de problemas de salud mental a lo largo de sus vidas. Hoy, gracias a la tecnología, tenemos información suficiente y las personas hablan con frecuencia de temas relacionados al malestar personal. Las redes sociales pareciera que nos conectan a un mundo deseado, pero la soledad alcanza a más personas a pesar de tener amigos en las redes: la conexión real de tener amigos se está perdiendo. El algoritmo nos muestra vidas “perfectas” y nuestro cerebro compara sin parar. El resultado: ansiedad, depresión, autoestima baja, FOMO, y esa sensación de “no estoy haciendo lo suficiente”. Y como si fuera poco, la atracción hipnotizante que cautiva y se puede pasar horas y horas conectadas a las redes o a los juegos virtuales, mientras el cerebro trabaja sin cesar para luego sentir sueño, irritabilidad, cansancio mental, dolor de cabeza, irritación ocular y otros malestares.',
                    'La pandemia nos enseñó que podíamos estar conectados y trabajar desde casa, conocer personas de otros países y tener información de todo tipo. Lo que no nos enseñó es cómo desconectarnos mentalmente de las redes sociales en internet, de las plataformas. En Perú y en gran parte de Latinoamérica, los problemas mentales aumentaron y ahora se habla de adicción a las redes sociales, a los juegos en línea. Buscar ayuda terapéutica para aliviar este problema es un reto, ya que las citas cuestan lo mismo que una semana de mercado, ello limita la intervención. Si bien en la actualidad se tiene más consciencia de lo que es tener mala salud mental, no basta con ello. ¿Qué hacemos entonces? Se debería tener en cuenta: normalizar pedir ayuda, poner límites digitales, sanar como familias y recuperar la conexión real con las personas.',
                    'En conclusión, la mala salud mental a consecuencia del mal uso de la tecnología es un problema que debe ser abatido por toda persona, familia e incluso el Estado; por ello no debemos olvidar que la salud mental es un derecho.',
                ],
                'cita' => 'La verdadera conexión no depende de una pantalla, sino del equilibrio entre la tecnología, las relaciones humanas y el cuidado permanente de nuestra salud mental.',
            ],
            [
                'slug' => 'gobernabilidad-contrapesos',
                'docente_nombre' => 'Carlos Jesús Alza Collantes',
                'titulo' => 'Presidenta y Senado del Mismo Color: ¿Gobernabilidad o Poder sin Contrapesos?',
                'parrafos' => [
                    'El Perú llega a un escenario inédito: la Presidencia de la República y la conducción del Senado recaen en dirigentes de una misma organización política. Para unos, esta coincidencia anuncia el fin de años de enfrentamiento entre el Ejecutivo y el Congreso; para otros, representa el riesgo de que la fiscalización se disuelva en la afinidad partidaria. Ninguna lectura debería adelantarse sin examen: la coincidencia de color político no constituye, por sí sola, una infracción constitucional. Lo que la Constitución exige no es que los poderes se comporten como adversarios, sino que cada uno conserve su competencia, responda por sus decisiones y actúe dentro del orden jurídico.',
                    'Conviene precisar, además, el alcance real de la fórmula “Senado del mismo color”: la agrupación oficialista es la primera fuerza en la Cámara Alta, mas no cuenta con mayoría absoluta, y las decisiones más relevantes —incluida la elección de altas autoridades— exigen mayorías calificadas que obligan a negociar con otras bancadas.',
                    'La afinidad política, bien conducida, puede traducirse en gobernabilidad genuina: agendas legislativas coordinadas, presupuestos aprobados con oportunidad y acuerdos sobre seguridad, salud y educación. La separación de poderes no equivale a enemistad permanente; comprende también una dimensión de cooperación orientada al bien común. Bajo ese marco, el Ejecutivo puede sustentar sus propuestas y el Senado revisarlas, corregirlas o rechazarlas, sin que la coincidencia partidaria elimine su independencia.',
                    'El riesgo aparece cuando la disciplina partidaria sustituye al juicio institucional. El Senado no fue creado para ratificar automáticamente al Poder Ejecutivo: su función revisora es sustantiva, no protocolar. Ese peligro se agrava en la designación de altas autoridades —Defensoría del Pueblo, Tribunal Constitucional, Banco Central de Reserva—, cargos que deben responder al mérito y no convertirse en cuotas repartidas entre bancadas.',
                    'La prueba decisiva no será, entonces, el color político de quienes ocupan los cargos, sino la forma en que ejerzan el poder. Publicidad de la agenda, calidad de la deliberación, transparencia en las designaciones, respeto a las minorías y rendición de cuentas son los criterios que permitirán distinguir la cooperación legítima de la subordinación institucional. La democracia no necesita poderes enemigos, pero tampoco poderes obedientes: necesita autoridades capaces de trabajar juntas, corregirse mutuamente y recordar que toda mayoría es temporal, mientras que la Constitución debe permanecer. La gobernabilidad y los contrapesos no son destinos automáticos: son prácticas que se construyen en cada ley, cada nombramiento y cada decisión.',
                ],
                'cita' => 'La coincidencia política no es, por sí misma, una amenaza a la democracia; lo que decide su carácter es cómo se ejerce el poder que de ella resulta.',
            ],
        ],
    ],

    'eventos_noticias' => [
        'titulo' => 'Eventos y Noticias',
        'intro' => 'Espacio destinado a difundir actividades, eventos y novedades relacionadas con la investigación, innovación y producción científica de la UPRIT. Aquí concentraremos capacitaciones, seminarios, congresos, convocatorias y otras iniciativas de interés inmediato para docentes, estudiantes, investigadores y visitantes.',
        'items' => [
            [
                'categoria' => 'Capacitación',
                'titulo' => 'Elaboración y Ejecución en Proyectos de Investigación',
                'descripcion' => 'Capacitación dirigida a la comunidad universitaria sobre la formulación, planificación y ejecución de proyectos de investigación.',
                'fecha' => '2026-08-26',
                'modalidad' => 'Virtual',
                'lugar' => 'Google Meet',
                'imagen' => null,
                'url' => 'https://meet.google.com/cig-axjq-uxn',
                'cta' => 'Unirse a la sesión',
            ],
            [
                'categoria' => 'Capacitación',
                'titulo' => 'Elaboración y Ejecución de Artículos Científicos y de Revisión Sistemática',
                'descripcion' => 'Capacitación dirigida a la comunidad universitaria sobre la redacción y ejecución de artículos científicos y artículos de revisión sistemática.',
                'fecha' => '2026-08-28',
                'modalidad' => 'Virtual',
                'lugar' => 'Google Meet',
                'imagen' => null,
                'url' => 'https://meet.google.com/tdj-tytt-zyr',
                'cta' => 'Unirse a la sesión',
            ],
            [
                'categoria' => 'Capacitación',
                'titulo' => 'Técnicas Estadísticas para Investigación en SPSS y RSTUDIO',
                'descripcion' => 'Capacitación dirigida a la comunidad universitaria sobre técnicas estadísticas aplicadas a la investigación con SPSS y RStudio.',
                'fecha' => '2026-08-31',
                'modalidad' => 'Virtual',
                'lugar' => 'Google Meet',
                'imagen' => null,
                'url' => 'https://meet.google.com/htm-fhem-hbr',
                'cta' => 'Unirse a la sesión',
            ],
        ],
    ],
];
